package pers.agreysky.idle.dto;

import javax.persistence.FetchType;
import javax.persistence.ManyToOne;

// Generated 2017-10-20 21:00:46 by Hibernate Tools 5.2.5.Final

/**
 * Advice generated by hbm2java
 */

public class Advice implements java.io.Serializable {

    private Integer id;
    private User user;
    private String advice;

    public Advice() {
    }

    public Advice(User user, String advice) {
        this.user = user;
        this.advice = advice;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    @ManyToOne(fetch = FetchType.EAGER)
    public void setUser(User user) {
        this.user = user;
    }
    public String getAdvice() {
        return this.advice;
    }

    public void setAdvice(String advice) {
        this.advice = advice;
    }

}
