package pers.agreysky.idle.dto;
// Generated 2017-10-20 21:00:46 by Hibernate Tools 5.2.5.Final

import javax.persistence.FetchType;
import javax.persistence.ManyToOne;

/**
 * Friends generated by hbm2java
 */
public class Friends implements java.io.Serializable {

    private Integer id;//id号
    private String name;//交友姓名
    private User user;//用户
    private String overview;//简介
    private String way;//联系方式
    private String contact;//具体联系方式
    private String sex;//性别
    private String label;//标签
    private String picture;//自拍

    public Friends() {
    }

    public Friends(User user, String overview, String way, String contact,
            String picture, String sex, String label, String name) {
        this.user = user;
        this.overview = overview;
        this.way = way;
        this.contact = contact;
        this.picture = picture;
        this.sex = sex;
        this.label = label;
        this.name = name;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    @ManyToOne(fetch = FetchType.EAGER)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    public String getOverview() {
        return this.overview;
    }

    public void setOverview(String overview) {
        this.overview = overview;
    }
    public String getWay() {
        return this.way;
    }

    public void setWay(String way) {
        this.way = way;
    }
    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getPicture() {
        return this.picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
