package pers.agreysky.idle.dto;
// Generated 2017-10-20 21:00:46 by Hibernate Tools 5.2.5.Final

import javax.persistence.FetchType;
import javax.persistence.ManyToOne;

/**
 * Jobs generated by hbm2java
 */
public class Jobs implements java.io.Serializable {

    private Integer id;
    private User user;
    private String name;//名称
    private String personNum;//人数
    private String overview;//描述
    private String welfare;//福利
    private String contact;//联系号码
    private String accDate;//结算方式
    private String reward;//报酬
    private String schedule;//时间
    private String pName;//负责人称呼
    private String type;//求职or供职

    public Jobs() {
    }

    public Jobs(User user, String name, String overview, String welfare,
            String contact, String personNum, String accDate, String reward,
            String schedule, String pName, String type) {
        this.user = user;
        this.name = name;
        this.overview = overview;
        this.welfare = welfare;
        this.contact = contact;
        this.personNum = personNum;
        this.accDate = accDate;
        this.reward = reward;
        this.schedule = schedule;
        this.pName = pName;
        this.type = type;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    @ManyToOne(fetch = FetchType.EAGER)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public String getOverview() {
        return this.overview;
    }

    public void setOverview(String overview) {
        this.overview = overview;
    }

    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getAccDate() {
        return accDate;
    }

    public void setAccDate(String accDate) {
        this.accDate = accDate;
    }

    public String getReward() {
        return reward;
    }

    public void setReward(String reward) {
        this.reward = reward;
    }

    public String getSchedule() {
        return schedule;
    }

    public void setSchedule(String schedule) {
        this.schedule = schedule;
    }

    public String getPersonNum() {
        return personNum;
    }

    public void setPersonNum(String personNum) {
        this.personNum = personNum;
    }

    public String getpName() {
        return pName;
    }

    public void setpName(String pName) {
        this.pName = pName;
    }

    public String getWelfare() {
        return welfare;
    }

    public void setWelfare(String welfare) {
        this.welfare = welfare;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
