package per.agreysky.org.vo;
// Generated 2017-9-25 21:10:18 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class Admin implements java.io.Serializable {

    private String adminId;
    private String name;
    private String password;
    private boolean sex;
    private Date born;
    private byte[] photo;

    public Admin() {
    }

    public Admin(String adminId, String name, String password, boolean sex,
            Date born) {
        this.adminId = adminId;
        this.name = name;
        this.password = password;
        this.sex = sex;
        this.born = born;
    }
    public Admin(String adminId, String name, String password, boolean sex,
            Date born, byte[] photo) {
        this.adminId = adminId;
        this.name = name;
        this.password = password;
        this.sex = sex;
        this.born = born;
        this.photo = photo;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isSex() {
        return sex;
    }

    public void setSex(boolean sex) {
        this.sex = sex;
    }

    public Date getBorn() {
        return born;
    }

    public void setBorn(Date born) {
        this.born = born;
    }

    public byte[] getPhoto() {
        return photo;
    }

    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

    public String getAdminId() {
        return adminId;
    }

    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }

}
