package per.agreysky.org.vo;
// Generated 2017-9-25 21:10:18 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Lend generated by hbm2java
 */
public class Lend implements java.io.Serializable {

    private Integer id;
    private int bookId;
    private String readerId;
    private String ISBN;
    private Date ltime;
    private boolean lendConfirm;
    private boolean returnRequest;

    public Lend() {
    }

    public Lend(int bookId, String readerId, String ISBN, Date ltime,
            boolean lendConfirm, boolean returnRequest) {
        this.bookId = bookId;
        this.readerId = readerId;
        this.ISBN = ISBN;
        this.ltime = ltime;
        this.lendConfirm = lendConfirm;
        this.returnRequest = returnRequest;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public int getBookId() {
        return this.bookId;
    }

    public void setBookId(int bookId) {
        this.bookId = bookId;
    }
    public String getReaderId() {
        return this.readerId;
    }

    public void setReaderId(String readerId) {
        this.readerId = readerId;
    }
    public String getISBN() {
        return this.ISBN;
    }

    public void setISBN(String ISBN) {
        this.ISBN = ISBN;
    }
    public Date getLtime() {
        return this.ltime;
    }

    public void setLtime(Date ltime) {
        this.ltime = ltime;
    }

    public boolean isLendConfirm() {
        return lendConfirm;
    }

    public void setLendConfirm(boolean lendConfirm) {
        this.lendConfirm = lendConfirm;
    }

    public boolean isReturnRequest() {
        return returnRequest;
    }

    public void setReturnRequest(boolean returnRequest) {
        this.returnRequest = returnRequest;
    }

}
