package per.agreysky.org.vo;
// Generated 2017-9-25 21:10:18 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

    private String readerId;
    private String name;
    private String password;
    private boolean sex;
    private Date born;
    private String spec;
    private int num;
    private byte[] photo;

    public Student() {
    }

    public Student(String readerId, String name, String password, boolean sex,
            Date born, String spec, int num) {
        this.readerId = readerId;
        this.name = name;
        this.password = password;
        this.sex = sex;
        this.born = born;
        this.spec = spec;
        this.num = num;
    }
    public Student(String readerId, String name, String password, boolean sex,
            Date born, String spec, int num, byte[] photo) {
        this.readerId = readerId;
        this.name = name;
        this.password = password;
        this.sex = sex;
        this.born = born;
        this.spec = spec;
        this.num = num;
        this.photo = photo;
    }

    public String getReaderId() {
        return this.readerId;
    }

    public void setReaderId(String readerId) {
        this.readerId = readerId;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public boolean isSex() {
        return this.sex;
    }

    public void setSex(boolean sex) {
        this.sex = sex;
    }
    public Date getBorn() {
        return this.born;
    }

    public void setBorn(Date born) {
        this.born = born;
    }
    public String getSpec() {
        return this.spec;
    }

    public void setSpec(String spec) {
        this.spec = spec;
    }
    public int getNum() {
        return this.num;
    }

    public void setNum(int num) {
        this.num = num;
    }
    public byte[] getPhoto() {
        return this.photo;
    }

    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
