package per.agreysky.bean;
// Generated 2018-4-18 17:18:14 by Hibernate Tools 5.2.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import per.agreysky.Interceptor.IAuditLog;

/**
 * Teachers generated by hbm2java
 */
@Entity
@Table(name = "teachers", catalog = "student"
)
public class Teachers implements java.io.Serializable, IAuditLog {

    private Long id;
    private String name;
    private Integer age;

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "name", length = 10)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "age")
    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    @Override
    public String getDetail() {
        return "名字：" + this.getName();
    }

    public Teachers() {
        super();
        this.id = new Date().getTime();
    }

}
