package pers.agreysky.idle.vo;
// Generated 2018-4-18 16:55:56 by Hibernate Tools 5.2.5.Final

/**
 * Advice generated by hbm2java
 */
public class Advice implements java.io.Serializable {

    private Integer id;
    private User user;
    private String advice;

    public Advice() {
    }

    public Advice(User user) {
        this.user = user;
    }
    public Advice(User user, String advice) {
        this.user = user;
        this.advice = advice;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    public String getAdvice() {
        return this.advice;
    }

    public void setAdvice(String advice) {
        this.advice = advice;
    }

}
