package pers.agreysky.idle.vo;
// Generated 2018-4-18 16:55:56 by Hibernate Tools 5.2.5.Final

/**
 * Fans generated by hbm2java
 */
public class Fans implements java.io.Serializable {

    private Integer interestId;
    private User userByOwnerId;
    private User userByFansId;

    public Fans() {
    }

    public Fans(User userByOwnerId, User userByFansId) {
        this.userByOwnerId = userByOwnerId;
        this.userByFansId = userByFansId;
    }

    public Integer getInterestId() {
        return this.interestId;
    }

    public void setInterestId(Integer interestId) {
        this.interestId = interestId;
    }
    public User getUserByOwnerId() {
        return this.userByOwnerId;
    }

    public void setUserByOwnerId(User userByOwnerId) {
        this.userByOwnerId = userByOwnerId;
    }
    public User getUserByFansId() {
        return this.userByFansId;
    }

    public void setUserByFansId(User userByFansId) {
        this.userByFansId = userByFansId;
    }

}
