package pers.agreysky.idle.vo;
// Generated 2018-4-18 16:55:56 by Hibernate Tools 5.2.5.Final

/**
 * Friends generated by hbm2java
 */
public class Friends implements java.io.Serializable {

    private Integer id;
    private User user;
    private String name;
    private String overview;
    private String way;
    private String contact;
    private String sex;
    private String label;
    private String picture;

    public Friends() {
    }

    public Friends(User user, String name, String overview, String way,
            String contact, String sex, String label, String picture) {
        this.user = user;
        this.name = name;
        this.overview = overview;
        this.way = way;
        this.contact = contact;
        this.sex = sex;
        this.label = label;
        this.picture = picture;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public String getOverview() {
        return this.overview;
    }

    public void setOverview(String overview) {
        this.overview = overview;
    }
    public String getWay() {
        return this.way;
    }

    public void setWay(String way) {
        this.way = way;
    }
    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }
    public String getPicture() {
        return this.picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

}
