package pers.agreysky.idle.vo;
// Generated 2018-4-18 16:55:56 by Hibernate Tools 5.2.5.Final

/**
 * Helps generated by hbm2java
 */
public class Helps implements java.io.Serializable {

    private Integer id;
    private User user;
    private String name;
    private String type;
    private String overview;
    private String way;
    private String contact;
    private String reward;

    public Helps() {
    }

    public Helps(User user, String name, String type, String overview,
            String way, String contact, String reward) {
        this.user = user;
        this.name = name;
        this.type = type;
        this.overview = overview;
        this.way = way;
        this.contact = contact;
        this.reward = reward;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }
    public String getOverview() {
        return this.overview;
    }

    public void setOverview(String overview) {
        this.overview = overview;
    }
    public String getWay() {
        return this.way;
    }

    public void setWay(String way) {
        this.way = way;
    }
    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getReward() {
        return this.reward;
    }

    public void setReward(String reward) {
        this.reward = reward;
    }

}
