package pers.agreysky.idle.vo;
// Generated 2018-4-18 16:55:56 by Hibernate Tools 5.2.5.Final

/**
 * Jobs generated by hbm2java
 */
public class Jobs implements java.io.Serializable {

    private Integer id;
    private User user;
    private String name;
    private String personNum;
    private String overview;
    private String welfare;
    private String contact;
    private String accDate;
    private String reward;
    private String schedule;
    private String pname;
    private String type;

    public Jobs() {
    }

    public Jobs(User user, String name, String personNum, String overview,
            String welfare, String contact, String accDate, String reward,
            String schedule, String pname, String type) {
        this.user = user;
        this.name = name;
        this.personNum = personNum;
        this.overview = overview;
        this.welfare = welfare;
        this.contact = contact;
        this.accDate = accDate;
        this.reward = reward;
        this.schedule = schedule;
        this.pname = pname;
        this.type = type;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public String getPersonNum() {
        return this.personNum;
    }

    public void setPersonNum(String personNum) {
        this.personNum = personNum;
    }
    public String getOverview() {
        return this.overview;
    }

    public void setOverview(String overview) {
        this.overview = overview;
    }
    public String getWelfare() {
        return this.welfare;
    }

    public void setWelfare(String welfare) {
        this.welfare = welfare;
    }
    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getAccDate() {
        return this.accDate;
    }

    public void setAccDate(String accDate) {
        this.accDate = accDate;
    }
    public String getReward() {
        return this.reward;
    }

    public void setReward(String reward) {
        this.reward = reward;
    }
    public String getSchedule() {
        return this.schedule;
    }

    public void setSchedule(String schedule) {
        this.schedule = schedule;
    }
    public String getPname() {
        return this.pname;
    }

    public void setPname(String pname) {
        this.pname = pname;
    }
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
