package pers.agreysky.idle.vo;
// Generated 2018-4-18 16:55:56 by Hibernate Tools 5.2.5.Final

/**
 * Likes generated by hbm2java
 */
public class Likes implements java.io.Serializable {

    private Integer likeId;
    private User userByLikerId;
    private User userByOwnerId;

    public Likes() {
    }

    public Likes(User userByLikerId, User userByOwnerId) {
        this.userByLikerId = userByLikerId;
        this.userByOwnerId = userByOwnerId;
    }

    public Integer getLikeId() {
        return this.likeId;
    }

    public void setLikeId(Integer likeId) {
        this.likeId = likeId;
    }
    public User getUserByLikerId() {
        return this.userByLikerId;
    }

    public void setUserByLikerId(User userByLikerId) {
        this.userByLikerId = userByLikerId;
    }
    public User getUserByOwnerId() {
        return this.userByOwnerId;
    }

    public void setUserByOwnerId(User userByOwnerId) {
        this.userByOwnerId = userByOwnerId;
    }

}
