package pers.agreysky.idle.vo;
// Generated 2018-4-18 16:55:56 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private Integer id;
    private String username;
    private String password;
    private String useremail;
    private String phone;
    private String picture;
    private String state;
    private String code;
    private String itemsNum;
    private String signature;
    private String beLikeNum;
    private String attentionNum;
    private String fansNum;
    private Set advices = new HashSet(0);
    private Set fansesForOwnerId = new HashSet(0);
    private Set fansesForFansId = new HashSet(0);
    private Set helpses = new HashSet(0);
    private Set likesesForLikerId = new HashSet(0);
    private Set itemses = new HashSet(0);
    private Set likesesForOwnerId = new HashSet(0);
    private Set jobses = new HashSet(0);
    private Set friendses = new HashSet(0);

    public User() {
    }

    public User(String username, String password, String phone, String state) {
        this.username = username;
        this.password = password;
        this.phone = phone;
        this.state = state;
    }
    public User(String username, String password, String useremail,
            String phone, String picture, String state, String code,
            String itemsNum, String signature, String beLikeNum,
            String attentionNum, String fansNum, Set advices,
            Set fansesForOwnerId, Set fansesForFansId, Set helpses,
            Set likesesForLikerId, Set itemses, Set likesesForOwnerId,
            Set jobses, Set friendses) {
        this.username = username;
        this.password = password;
        this.useremail = useremail;
        this.phone = phone;
        this.picture = picture;
        this.state = state;
        this.code = code;
        this.itemsNum = itemsNum;
        this.signature = signature;
        this.beLikeNum = beLikeNum;
        this.attentionNum = attentionNum;
        this.fansNum = fansNum;
        this.advices = advices;
        this.fansesForOwnerId = fansesForOwnerId;
        this.fansesForFansId = fansesForFansId;
        this.helpses = helpses;
        this.likesesForLikerId = likesesForLikerId;
        this.itemses = itemses;
        this.likesesForOwnerId = likesesForOwnerId;
        this.jobses = jobses;
        this.friendses = friendses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    public String getUseremail() {
        return this.useremail;
    }

    public void setUseremail(String useremail) {
        this.useremail = useremail;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getPicture() {
        return this.picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }
    public String getItemsNum() {
        return this.itemsNum;
    }

    public void setItemsNum(String itemsNum) {
        this.itemsNum = itemsNum;
    }
    public String getSignature() {
        return this.signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }
    public String getBeLikeNum() {
        return this.beLikeNum;
    }

    public void setBeLikeNum(String beLikeNum) {
        this.beLikeNum = beLikeNum;
    }
    public String getAttentionNum() {
        return this.attentionNum;
    }

    public void setAttentionNum(String attentionNum) {
        this.attentionNum = attentionNum;
    }
    public String getFansNum() {
        return this.fansNum;
    }

    public void setFansNum(String fansNum) {
        this.fansNum = fansNum;
    }
    public Set getAdvices() {
        return this.advices;
    }

    public void setAdvices(Set advices) {
        this.advices = advices;
    }
    public Set getFansesForOwnerId() {
        return this.fansesForOwnerId;
    }

    public void setFansesForOwnerId(Set fansesForOwnerId) {
        this.fansesForOwnerId = fansesForOwnerId;
    }
    public Set getFansesForFansId() {
        return this.fansesForFansId;
    }

    public void setFansesForFansId(Set fansesForFansId) {
        this.fansesForFansId = fansesForFansId;
    }
    public Set getHelpses() {
        return this.helpses;
    }

    public void setHelpses(Set helpses) {
        this.helpses = helpses;
    }
    public Set getLikesesForLikerId() {
        return this.likesesForLikerId;
    }

    public void setLikesesForLikerId(Set likesesForLikerId) {
        this.likesesForLikerId = likesesForLikerId;
    }
    public Set getItemses() {
        return this.itemses;
    }

    public void setItemses(Set itemses) {
        this.itemses = itemses;
    }
    public Set getLikesesForOwnerId() {
        return this.likesesForOwnerId;
    }

    public void setLikesesForOwnerId(Set likesesForOwnerId) {
        this.likesesForOwnerId = likesesForOwnerId;
    }
    public Set getJobses() {
        return this.jobses;
    }

    public void setJobses(Set jobses) {
        this.jobses = jobses;
    }
    public Set getFriendses() {
        return this.friendses;
    }

    public void setFriendses(Set friendses) {
        this.friendses = friendses;
    }

}
